//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypographyWCFClient.WorkClassersRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Typography_WCF")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TypographyWCFClient.WorkClassersRef.Person clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TypographyWCFClient.WorkClassersRef.Service serviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TypographyWCFClient.WorkClassersRef.Person client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                if ((this.countField.Equals(value) != true)) {
                    this.countField = value;
                    this.RaisePropertyChanged("count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TypographyWCFClient.WorkClassersRef.Service service {
            get {
                return this.serviceField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceField, value) != true)) {
                    this.serviceField = value;
                    this.RaisePropertyChanged("service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Typography_WCF")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birthdayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tokenDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthdayDate {
            get {
                return this.birthdayDateField;
            }
            set {
                if ((this.birthdayDateField.Equals(value) != true)) {
                    this.birthdayDateField = value;
                    this.RaisePropertyChanged("birthdayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telephoneField, value) != true)) {
                    this.telephoneField = value;
                    this.RaisePropertyChanged("telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tokenDate {
            get {
                return this.tokenDateField;
            }
            set {
                if ((this.tokenDateField.Equals(value) != true)) {
                    this.tokenDateField = value;
                    this.RaisePropertyChanged("tokenDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/Typography_WCF")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TypographyWCFClient.WorkClassersRef.PrintType printTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TypographyWCFClient.WorkClassersRef.PrintType printType {
            get {
                return this.printTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.printTypeField, value) != true)) {
                    this.printTypeField = value;
                    this.RaisePropertyChanged("printType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintType", Namespace="http://schemas.datacontract.org/2004/07/Typography_WCF")]
    [System.SerializableAttribute()]
    public partial class PrintType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/Typography_WCF")]
    [System.SerializableAttribute()]
    public partial class ChatMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TypographyWCFClient.WorkClassersRef.Person authorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TypographyWCFClient.WorkClassersRef.Order orderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TypographyWCFClient.WorkClassersRef.Person author {
            get {
                return this.authorField;
            }
            set {
                if ((object.ReferenceEquals(this.authorField, value) != true)) {
                    this.authorField = value;
                    this.RaisePropertyChanged("author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TypographyWCFClient.WorkClassersRef.Order order {
            get {
                return this.orderField;
            }
            set {
                if ((object.ReferenceEquals(this.orderField, value) != true)) {
                    this.orderField = value;
                    this.RaisePropertyChanged("order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sale", Namespace="http://schemas.datacontract.org/2004/07/Typography_WCF")]
    [System.SerializableAttribute()]
    public partial class Sale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int percentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateEnd {
            get {
                return this.dateEndField;
            }
            set {
                if ((this.dateEndField.Equals(value) != true)) {
                    this.dateEndField = value;
                    this.RaisePropertyChanged("dateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateStart {
            get {
                return this.dateStartField;
            }
            set {
                if ((this.dateStartField.Equals(value) != true)) {
                    this.dateStartField = value;
                    this.RaisePropertyChanged("dateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int percent {
            get {
                return this.percentField;
            }
            set {
                if ((this.percentField.Equals(value) != true)) {
                    this.percentField = value;
                    this.RaisePropertyChanged("percent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkClassersRef.IClasses")]
    public interface IClasses {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/GetChatMessagesOfOrder", ReplyAction="http://tempuri.org/IClasses/GetChatMessagesOfOrderResponse")]
        TypographyWCFClient.WorkClassersRef.ChatMessage[] GetChatMessagesOfOrder(TypographyWCFClient.WorkClassersRef.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/GetChatMessagesOfOrder", ReplyAction="http://tempuri.org/IClasses/GetChatMessagesOfOrderResponse")]
        System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.ChatMessage[]> GetChatMessagesOfOrderAsync(TypographyWCFClient.WorkClassersRef.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getCurrentUser", ReplyAction="http://tempuri.org/IClasses/getCurrentUserResponse")]
        TypographyWCFClient.WorkClassersRef.Person getCurrentUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getCurrentUser", ReplyAction="http://tempuri.org/IClasses/getCurrentUserResponse")]
        System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Person> getCurrentUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getOrdersOfCurrentUser", ReplyAction="http://tempuri.org/IClasses/getOrdersOfCurrentUserResponse")]
        TypographyWCFClient.WorkClassersRef.Order[] getOrdersOfCurrentUser(TypographyWCFClient.WorkClassersRef.Person user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getOrdersOfCurrentUser", ReplyAction="http://tempuri.org/IClasses/getOrdersOfCurrentUserResponse")]
        System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Order[]> getOrdersOfCurrentUserAsync(TypographyWCFClient.WorkClassersRef.Person user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/changePwd", ReplyAction="http://tempuri.org/IClasses/changePwdResponse")]
        void changePwd(int personID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/changePwd", ReplyAction="http://tempuri.org/IClasses/changePwdResponse")]
        System.Threading.Tasks.Task changePwdAsync(int personID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/addChatMessage", ReplyAction="http://tempuri.org/IClasses/addChatMessageResponse")]
        void addChatMessage(TypographyWCFClient.WorkClassersRef.ChatMessage chatMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/addChatMessage", ReplyAction="http://tempuri.org/IClasses/addChatMessageResponse")]
        System.Threading.Tasks.Task addChatMessageAsync(TypographyWCFClient.WorkClassersRef.ChatMessage chatMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/addOrder", ReplyAction="http://tempuri.org/IClasses/addOrderResponse")]
        void addOrder(TypographyWCFClient.WorkClassersRef.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/addOrder", ReplyAction="http://tempuri.org/IClasses/addOrderResponse")]
        System.Threading.Tasks.Task addOrderAsync(TypographyWCFClient.WorkClassersRef.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getOrdersByDate", ReplyAction="http://tempuri.org/IClasses/getOrdersByDateResponse")]
        TypographyWCFClient.WorkClassersRef.Order[] getOrdersByDate(int PersonID, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getOrdersByDate", ReplyAction="http://tempuri.org/IClasses/getOrdersByDateResponse")]
        System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Order[]> getOrdersByDateAsync(int PersonID, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/auth", ReplyAction="http://tempuri.org/IClasses/authResponse")]
        int auth(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/auth", ReplyAction="http://tempuri.org/IClasses/authResponse")]
        System.Threading.Tasks.Task<int> authAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/logout", ReplyAction="http://tempuri.org/IClasses/logoutResponse")]
        int logout(int personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/logout", ReplyAction="http://tempuri.org/IClasses/logoutResponse")]
        System.Threading.Tasks.Task<int> logoutAsync(int personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getSales", ReplyAction="http://tempuri.org/IClasses/getSalesResponse")]
        TypographyWCFClient.WorkClassersRef.Sale[] getSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getSales", ReplyAction="http://tempuri.org/IClasses/getSalesResponse")]
        System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Sale[]> getSalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getServices", ReplyAction="http://tempuri.org/IClasses/getServicesResponse")]
        TypographyWCFClient.WorkClassersRef.Service[] getServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasses/getServices", ReplyAction="http://tempuri.org/IClasses/getServicesResponse")]
        System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Service[]> getServicesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassesChannel : TypographyWCFClient.WorkClassersRef.IClasses, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassesClient : System.ServiceModel.ClientBase<TypographyWCFClient.WorkClassersRef.IClasses>, TypographyWCFClient.WorkClassersRef.IClasses {
        
        public ClassesClient() {
        }
        
        public ClassesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TypographyWCFClient.WorkClassersRef.ChatMessage[] GetChatMessagesOfOrder(TypographyWCFClient.WorkClassersRef.Order order) {
            return base.Channel.GetChatMessagesOfOrder(order);
        }
        
        public System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.ChatMessage[]> GetChatMessagesOfOrderAsync(TypographyWCFClient.WorkClassersRef.Order order) {
            return base.Channel.GetChatMessagesOfOrderAsync(order);
        }
        
        public TypographyWCFClient.WorkClassersRef.Person getCurrentUser(string login, string password) {
            return base.Channel.getCurrentUser(login, password);
        }
        
        public System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Person> getCurrentUserAsync(string login, string password) {
            return base.Channel.getCurrentUserAsync(login, password);
        }
        
        public TypographyWCFClient.WorkClassersRef.Order[] getOrdersOfCurrentUser(TypographyWCFClient.WorkClassersRef.Person user) {
            return base.Channel.getOrdersOfCurrentUser(user);
        }
        
        public System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Order[]> getOrdersOfCurrentUserAsync(TypographyWCFClient.WorkClassersRef.Person user) {
            return base.Channel.getOrdersOfCurrentUserAsync(user);
        }
        
        public void changePwd(int personID, string password) {
            base.Channel.changePwd(personID, password);
        }
        
        public System.Threading.Tasks.Task changePwdAsync(int personID, string password) {
            return base.Channel.changePwdAsync(personID, password);
        }
        
        public void addChatMessage(TypographyWCFClient.WorkClassersRef.ChatMessage chatMessage) {
            base.Channel.addChatMessage(chatMessage);
        }
        
        public System.Threading.Tasks.Task addChatMessageAsync(TypographyWCFClient.WorkClassersRef.ChatMessage chatMessage) {
            return base.Channel.addChatMessageAsync(chatMessage);
        }
        
        public void addOrder(TypographyWCFClient.WorkClassersRef.Order order) {
            base.Channel.addOrder(order);
        }
        
        public System.Threading.Tasks.Task addOrderAsync(TypographyWCFClient.WorkClassersRef.Order order) {
            return base.Channel.addOrderAsync(order);
        }
        
        public TypographyWCFClient.WorkClassersRef.Order[] getOrdersByDate(int PersonID, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.getOrdersByDate(PersonID, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Order[]> getOrdersByDateAsync(int PersonID, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.getOrdersByDateAsync(PersonID, startDate, endDate);
        }
        
        public int auth(string login, string password) {
            return base.Channel.auth(login, password);
        }
        
        public System.Threading.Tasks.Task<int> authAsync(string login, string password) {
            return base.Channel.authAsync(login, password);
        }
        
        public int logout(int personID) {
            return base.Channel.logout(personID);
        }
        
        public System.Threading.Tasks.Task<int> logoutAsync(int personID) {
            return base.Channel.logoutAsync(personID);
        }
        
        public TypographyWCFClient.WorkClassersRef.Sale[] getSales() {
            return base.Channel.getSales();
        }
        
        public System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Sale[]> getSalesAsync() {
            return base.Channel.getSalesAsync();
        }
        
        public TypographyWCFClient.WorkClassersRef.Service[] getServices() {
            return base.Channel.getServices();
        }
        
        public System.Threading.Tasks.Task<TypographyWCFClient.WorkClassersRef.Service[]> getServicesAsync() {
            return base.Channel.getServicesAsync();
        }
    }
}
